### ISSUE TITLE
provide documentation on adding a copr repo as 3rd part repo

### ISSUE THREAD

**Issue by coiby** [osbuild/guides#67]
[Managing repositories - OSBuild guides](https://www.osbuild.org/guides/user-guide/managing-repositories.html) doesn't provide the documentation on adding a copr repo as 3rd part repo and neither does `man composer-cli-sources`,

Btw if I `composer-cli sources add` a TOML as follows,
```toml
id="kexec-tools-crashkernel"
name="kexec-tools-crashkernel"
url="https://download.copr.fedorainfracloud.org/results/coiby/kexec-tools-crashkernel/fedora-34-x86_64"
type="yum-baseurl"
check_gpg = false
check_ssl = false
system = false
```
Running `composer-cli compose start crashkernel qcow2` gives the following error,
```                          
ERROR: DepsolveError: DNF error occured: RepoError: Error occurred when setting up repo: Failed to download metadata for repo '4': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
